; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATtiny814]
platform = atmelmegaavr
board = ATtiny814
framework = arduino
upload_port = COM3
upload_speed = 115200
upload_protocol = serialupdi
monitor_speed = 115200
build_unflags = -DMILLIS_USE_TIMERD0
build_flags = 
    -DMILLIS_USE_TIMERB0
    -DMOTOR_DUTY=95
    -DDEAD_TIME_TICKS=2